language: php

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 7.0
      env: PACT_DISABLE_ZEND_ASSERTIONS=true
    - php: 7.1
      env: PACT_DISABLE_ZEND_ASSERTIONS=true
    - php: 7.2
      env: PACT_DISABLE_ZEND_ASSERTIONS=true
    - php: nightly
      env: PACT_DISABLE_ZEND_ASSERTIONS=true
  allow_failures:
    - php: nightly
    - php: hhvm

install:
  - composer install

script:
  - if [ -z "$PACT_DISABLE_ZEND_ASSERTIONS" ]; then php -dzend.assertions=1 ./vendor/bin/phpunit -v --coverage-text; fi
  - if [ "$PACT_DISABLE_ZEND_ASSERTIONS" = "true" ]; then php -dzend.assertions=0 ./vendor/bin/phpunit -v --coverage-text; fi
